<?php
  /*$example = $this->example;

  if ($example) {
    echo '<pre>';
    print_r($example);
    echo '</pre>';
  }*/
?>

    <div class="row">
        <div class="center-block col-xs-6 col-sm-6 col-md-6 col-lg-6" style="float: none">
            <div id="form" class=""></div>
        </div>
    </div>

    <div class="row">
        <div class="center-block col-xs-12 col-sm-12 col-md-12 col-lg-12" style="float: none">
            <div id="list" class=""></div>
        </div>
    </div>

<?php echo $this->headScript()->appendFile('/app/ext-all-debug.js', 'text/javascript')
    ->appendFile('/app/app.js', 'text/javascript') ?>

