<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>crud</title>
  <?php echo $this->headLink()->appendStylesheet('/assets/bootstrap/css/bootstrap.min.css') ?>
  <?php echo $this->headLink()->appendStylesheet('/app/ext-4/resources/css/ext-all.css') ?>
  <?php echo $this->headScript()->appendFile('/app/ext-all.js', 'text/javascript')
                                ->appendFile('/app/app.js', 'text/javascript') ?>
</head>
<body>
  <div class="container" >
    <?php echo $this->layout()->content ?>
  </div>
</body>
</html>
