<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>crud</title>
  <style>
    .signinpanel {
      margin: 10% auto 0 auto;
    }
    .custom {
      width: 330px !important;
    }
  </style>
  <?php echo $this->headLink()->appendStylesheet('/assets/bootstrap/css/bootstrap.min.css') ?>
  <?php echo $this->headLink()->appendStylesheet('/app/ext-4/resources/css/ext-all.css') ?>
  
</head>
<body>
  <div class="container" >
    <?php echo $this->layout()->content ?>
  </div>
</body>
</html>
