

<div class="signinpanel">
    <div class="row">
        <div class="center-block col-xs-4 col-sm-4 col-lg-4 col-md-4" style="float: none">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group" >
                        <div class="input-group" style="margin-top: 15px">
                            <span class="input-group-addon glyphicon glyphicon-user" id="basic-addon1"></span>
                            <input class="form-control" type="text" placeholder="usuario" id="user" aria-describedby="basic-addon1">
                        </div>
                        <div class="input-group " style="margin-top: 15px">
                            <span class="input-group-addon glyphicon glyphicon-asterisk distantbox" id="basic-addon2" ></span>
                            <input class="form-control" type="password" placeholder="contraseña" id="password" aria-describedby="basic-addon2">
                        </div>
                        <div class="input-group" style="margin-top: 15px" id="btnLogin">
                            <button type="button" class="btn btn-primary custom" >
                                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> ingresar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->headScript()->appendFile('/app/ext-all.js', 'text/javascript')
    ->appendFile('/app/login.js', 'text/javascript') ?>
